// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:4de693f1-1d21-4251-b66a-b79788130e4e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_aCGPp5SD8",
    "aws_user_pools_web_client_id": "kih6th6mjfivrhisimmkplm6",
    "oauth": {}
};


export default awsmobile;
